version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - aws s3 sync dist s3://telispire-static-web-site --delete
 post_build:
   commands:
     - echo "post_build step"